[package]
publish = false
name = "main"
version = "0.5.3"
edition = "2021"

[workspace]

[dependencies]
anyhow = "1.0.72"
bytecount = "=0.6.3"

[dependencies.shared]
path = "../../shared"

[[bin]]
name = "main"
path = "main.rs"

[profile.release]
debug = true
