[package]
publish = false
name = "main"
version = "0.6.7"
edition = "2021"

[workspace]

[dependencies]
anyhow = "1.0.72"
bytecount = "=0.6.7"

[dependencies.shared]
path = "../../shared"

[[bin]]
name = "main"
path = "main.rs"

[profile.release]
debug = true
codegen-units = 1
lto = "fat"
