[[bench]]
model = "count"
name = "huge-en-that"
regex = 'that'
haystack = { path = "opensubtitles/en-huge.txt" }
count = 865
engines = [
  "libc/memmem/oneshot",
  "rust/jetscii/memmem/oneshot",
  "rust/jetscii/memmem/prebuilt",
  "rust/memchr/memmem/oneshot",
  "rust/memchr/memmem/prebuilt",
  "rust/memchr/memmem/twoway",
  "rust/memchr/memmem/rabinkarp",
  "rust/memchr/memmem/shiftor",
  "rust/memchr/memmem/wasm32",
  "rust/memchrold/memmem/oneshot",
  "rust/memchrold/memmem/prebuilt",
  "rust/std/memmem/oneshot",
  "rust/std/memmem/prebuilt",
  "stringzilla/memmem/oneshot",
]

[[bench]]
model = "count"
name = "huge-en-you"
regex = 'you'
haystack = { path = "opensubtitles/en-huge.txt" }
count = 5009
engines = [
  "libc/memmem/oneshot",
  "rust/jetscii/memmem/oneshot",
  "rust/jetscii/memmem/prebuilt",
  "rust/memchr/memmem/oneshot",
  "rust/memchr/memmem/prebuilt",
  "rust/memchr/memmem/twoway",
  "rust/memchr/memmem/rabinkarp",
  "rust/memchr/memmem/shiftor",
  "rust/memchr/memmem/wasm32",
  "rust/memchrold/memmem/oneshot",
  "rust/memchrold/memmem/prebuilt",
  "rust/std/memmem/oneshot",
  "rust/std/memmem/prebuilt",
  "stringzilla/memmem/oneshot",
]

[[bench]]
model = "count"
name = "huge-en-one-space"
regex = ' '
haystack = { path = "opensubtitles/en-huge.txt" }
count = 96_606
engines = [
  "libc/memmem/oneshot",
  "rust/jetscii/memmem/oneshot",
  "rust/jetscii/memmem/prebuilt",
  "rust/memchr/memmem/oneshot",
  "rust/memchr/memmem/prebuilt",
  "rust/memchr/memmem/twoway",
  "rust/memchr/memmem/rabinkarp",
  "rust/memchr/memmem/shiftor",
  "rust/memchr/memmem/wasm32",
  "rust/memchrold/memmem/oneshot",
  "rust/memchrold/memmem/prebuilt",
  "rust/std/memmem/oneshot",
  "rust/std/memmem/prebuilt",
  "stringzilla/memmem/oneshot",
]

[[bench]]
model = "count"
name = "huge-ru-that"
regex = 'что'
haystack = { path = "opensubtitles/ru-huge.txt" }
count = 998
engines = [
  "libc/memmem/oneshot",
  "rust/jetscii/memmem/oneshot",
  "rust/jetscii/memmem/prebuilt",
  "rust/memchr/memmem/oneshot",
  "rust/memchr/memmem/prebuilt",
  "rust/memchr/memmem/twoway",
  "rust/memchr/memmem/rabinkarp",
  "rust/memchr/memmem/shiftor",
  "rust/memchr/memmem/wasm32",
  "rust/memchrold/memmem/oneshot",
  "rust/memchrold/memmem/prebuilt",
  "rust/std/memmem/oneshot",
  "rust/std/memmem/prebuilt",
  "stringzilla/memmem/oneshot",
]

[[bench]]
model = "count"
name = "huge-ru-not"
regex = 'не'
haystack = { path = "opensubtitles/ru-huge.txt" }
count = 3092
engines = [
  "libc/memmem/oneshot",
  "rust/jetscii/memmem/oneshot",
  "rust/jetscii/memmem/prebuilt",
  "rust/memchr/memmem/oneshot",
  "rust/memchr/memmem/prebuilt",
  "rust/memchr/memmem/twoway",
  "rust/memchr/memmem/rabinkarp",
  "rust/memchr/memmem/shiftor",
  "rust/memchr/memmem/wasm32",
  "rust/memchrold/memmem/oneshot",
  "rust/memchrold/memmem/prebuilt",
  "rust/std/memmem/oneshot",
  "rust/std/memmem/prebuilt",
  "stringzilla/memmem/oneshot",
]

[[bench]]
model = "count"
name = "huge-ru-one-space"
regex = ' '
haystack = { path = "opensubtitles/ru-huge.txt" }
count = 46_941
engines = [
  "libc/memmem/oneshot",
  "rust/jetscii/memmem/oneshot",
  "rust/jetscii/memmem/prebuilt",
  "rust/memchr/memmem/oneshot",
  "rust/memchr/memmem/prebuilt",
  "rust/memchr/memmem/twoway",
  "rust/memchr/memmem/rabinkarp",
  "rust/memchr/memmem/shiftor",
  "rust/memchr/memmem/wasm32",
  "rust/memchrold/memmem/oneshot",
  "rust/memchrold/memmem/prebuilt",
  "rust/std/memmem/oneshot",
  "rust/std/memmem/prebuilt",
  "stringzilla/memmem/oneshot",
]

[[bench]]
model = "count"
name = "huge-zh-that"
regex = '那'
haystack = { path = "opensubtitles/zh-huge.txt" }
count = 1056
engines = [
  "libc/memmem/oneshot",
  "rust/jetscii/memmem/oneshot",
  "rust/jetscii/memmem/prebuilt",
  "rust/memchr/memmem/oneshot",
  "rust/memchr/memmem/prebuilt",
  "rust/memchr/memmem/twoway",
  "rust/memchr/memmem/rabinkarp",
  "rust/memchr/memmem/shiftor",
  "rust/memchr/memmem/wasm32",
  "rust/memchrold/memmem/oneshot",
  "rust/memchrold/memmem/prebuilt",
  "rust/std/memmem/oneshot",
  "rust/std/memmem/prebuilt",
  "stringzilla/memmem/oneshot",
]

[[bench]]
model = "count"
name = "huge-zh-do-not"
regex = '不'
haystack = { path = "opensubtitles/zh-huge.txt" }
count = 2751
engines = [
  "libc/memmem/oneshot",
  "rust/jetscii/memmem/oneshot",
  "rust/jetscii/memmem/prebuilt",
  "rust/memchr/memmem/oneshot",
  "rust/memchr/memmem/prebuilt",
  "rust/memchr/memmem/twoway",
  "rust/memchr/memmem/rabinkarp",
  "rust/memchr/memmem/shiftor",
  "rust/memchr/memmem/wasm32",
  "rust/memchrold/memmem/oneshot",
  "rust/memchrold/memmem/prebuilt",
  "rust/std/memmem/oneshot",
  "rust/std/memmem/prebuilt",
  "stringzilla/memmem/oneshot",
]

[[bench]]
model = "count"
name = "huge-zh-one-space"
regex = ' '
haystack = { path = "opensubtitles/zh-huge.txt" }
count = 17_232
engines = [
  "libc/memmem/oneshot",
  "rust/jetscii/memmem/oneshot",
  "rust/jetscii/memmem/prebuilt",
  "rust/memchr/memmem/oneshot",
  "rust/memchr/memmem/prebuilt",
  "rust/memchr/memmem/twoway",
  "rust/memchr/memmem/rabinkarp",
  "rust/memchr/memmem/shiftor",
  "rust/memchr/memmem/wasm32",
  "rust/memchrold/memmem/oneshot",
  "rust/memchrold/memmem/prebuilt",
  "rust/std/memmem/oneshot",
  "rust/std/memmem/prebuilt",
  "stringzilla/memmem/oneshot",
]
