[[bench]]
model = "count"
name = "huge-en-john-watson"
regex = 'John Watson'
haystack = { path = "opensubtitles/en-huge.txt" }
count = 0
engines = [
  "libc/memmem/oneshot",
  "rust/jetscii/memmem/oneshot",
  "rust/jetscii/memmem/prebuilt",
  "rust/memchr/memmem/oneshot",
  "rust/memchr/memmem/prebuilt",
  "rust/memchr/memmem/twoway",
  "rust/memchr/memmem/rabinkarp",
  "rust/memchr/memmem/shiftor",
  "rust/memchr/memmem/wasm32",
  "rust/memchrold/memmem/oneshot",
  "rust/memchrold/memmem/prebuilt",
  "rust/sliceslice/memmem/oneshot",
  "rust/sliceslice/memmem/prebuilt",
  "rust/std/memmem/oneshot",
  "rust/std/memmem/prebuilt",
  "stringzilla/memmem/oneshot",
]

[[bench]]
model = "count"
name = "huge-en-all-common-bytes"
regex = 'sternness'
haystack = { path = "opensubtitles/en-huge.txt" }
count = 0
engines = [
  "libc/memmem/oneshot",
  "rust/jetscii/memmem/oneshot",
  "rust/jetscii/memmem/prebuilt",
  "rust/memchr/memmem/oneshot",
  "rust/memchr/memmem/prebuilt",
  "rust/memchr/memmem/twoway",
  "rust/memchr/memmem/rabinkarp",
  "rust/memchr/memmem/shiftor",
  "rust/memchr/memmem/wasm32",
  "rust/memchrold/memmem/oneshot",
  "rust/memchrold/memmem/prebuilt",
  "rust/sliceslice/memmem/oneshot",
  "rust/sliceslice/memmem/prebuilt",
  "rust/std/memmem/oneshot",
  "rust/std/memmem/prebuilt",
  "stringzilla/memmem/oneshot",
]

[[bench]]
model = "count"
name = "huge-en-some-rare-bytes"
regex = 'quartz'
haystack = { path = "opensubtitles/en-huge.txt" }
count = 0
engines = [
  "libc/memmem/oneshot",
  "rust/jetscii/memmem/oneshot",
  "rust/jetscii/memmem/prebuilt",
  "rust/memchr/memmem/oneshot",
  "rust/memchr/memmem/prebuilt",
  "rust/memchr/memmem/twoway",
  "rust/memchr/memmem/rabinkarp",
  "rust/memchr/memmem/shiftor",
  "rust/memchr/memmem/wasm32",
  "rust/memchrold/memmem/oneshot",
  "rust/memchrold/memmem/prebuilt",
  "rust/sliceslice/memmem/oneshot",
  "rust/sliceslice/memmem/prebuilt",
  "rust/std/memmem/oneshot",
  "rust/std/memmem/prebuilt",
  "stringzilla/memmem/oneshot",
]

[[bench]]
model = "count"
name = "huge-en-two-space"
regex = '  '
haystack = { path = "opensubtitles/en-huge.txt" }
count = 0
engines = [
  "libc/memmem/oneshot",
  "rust/jetscii/memmem/oneshot",
  "rust/jetscii/memmem/prebuilt",
  "rust/memchr/memmem/oneshot",
  "rust/memchr/memmem/prebuilt",
  "rust/memchr/memmem/twoway",
  "rust/memchr/memmem/rabinkarp",
  "rust/memchr/memmem/shiftor",
  "rust/memchr/memmem/wasm32",
  "rust/memchrold/memmem/oneshot",
  "rust/memchrold/memmem/prebuilt",
  "rust/sliceslice/memmem/oneshot",
  "rust/sliceslice/memmem/prebuilt",
  "rust/std/memmem/oneshot",
  "rust/std/memmem/prebuilt",
  "stringzilla/memmem/oneshot",
]

[[bench]]
model = "count"
name = "teeny-en-john-watson"
regex = 'John Watson'
haystack = { path = "opensubtitles/en-teeny.txt" }
count = 0
engines = [
  "libc/memmem/oneshot",
  "rust/jetscii/memmem/oneshot",
  "rust/jetscii/memmem/prebuilt",
  "rust/memchr/memmem/oneshot",
  "rust/memchr/memmem/prebuilt",
  "rust/memchr/memmem/twoway",
  "rust/memchr/memmem/rabinkarp",
  "rust/memchr/memmem/shiftor",
  "rust/memchr/memmem/wasm32",
  "rust/memchrold/memmem/oneshot",
  "rust/memchrold/memmem/prebuilt",
  "rust/sliceslice/memmem/oneshot",
  "rust/sliceslice/memmem/prebuilt",
  "rust/std/memmem/oneshot",
  "rust/std/memmem/prebuilt",
  "stringzilla/memmem/oneshot",
]

[[bench]]
model = "count"
name = "teeny-en-all-common-bytes"
regex = 'sternness'
haystack = { path = "opensubtitles/en-teeny.txt" }
count = 0
engines = [
  "libc/memmem/oneshot",
  "rust/jetscii/memmem/oneshot",
  "rust/jetscii/memmem/prebuilt",
  "rust/memchr/memmem/oneshot",
  "rust/memchr/memmem/prebuilt",
  "rust/memchr/memmem/twoway",
  "rust/memchr/memmem/rabinkarp",
  "rust/memchr/memmem/shiftor",
  "rust/memchr/memmem/wasm32",
  "rust/memchrold/memmem/oneshot",
  "rust/memchrold/memmem/prebuilt",
  "rust/sliceslice/memmem/oneshot",
  "rust/sliceslice/memmem/prebuilt",
  "rust/std/memmem/oneshot",
  "rust/std/memmem/prebuilt",
  "stringzilla/memmem/oneshot",
]

[[bench]]
model = "count"
name = "teeny-en-some-rare-bytes"
regex = 'quartz'
haystack = { path = "opensubtitles/en-teeny.txt" }
count = 0
engines = [
  "libc/memmem/oneshot",
  "rust/jetscii/memmem/oneshot",
  "rust/jetscii/memmem/prebuilt",
  "rust/memchr/memmem/oneshot",
  "rust/memchr/memmem/prebuilt",
  "rust/memchr/memmem/twoway",
  "rust/memchr/memmem/rabinkarp",
  "rust/memchr/memmem/shiftor",
  "rust/memchr/memmem/wasm32",
  "rust/memchrold/memmem/oneshot",
  "rust/memchrold/memmem/prebuilt",
  "rust/sliceslice/memmem/oneshot",
  "rust/sliceslice/memmem/prebuilt",
  "rust/std/memmem/oneshot",
  "rust/std/memmem/prebuilt",
  "stringzilla/memmem/oneshot",
]

[[bench]]
model = "count"
name = "teeny-en-two-space"
regex = '  '
haystack = { path = "opensubtitles/en-teeny.txt" }
count = 0
engines = [
  "libc/memmem/oneshot",
  "rust/jetscii/memmem/oneshot",
  "rust/jetscii/memmem/prebuilt",
  "rust/memchr/memmem/oneshot",
  "rust/memchr/memmem/prebuilt",
  "rust/memchr/memmem/twoway",
  "rust/memchr/memmem/rabinkarp",
  "rust/memchr/memmem/shiftor",
  "rust/memchr/memmem/wasm32",
  "rust/memchrold/memmem/oneshot",
  "rust/memchrold/memmem/prebuilt",
  "rust/sliceslice/memmem/oneshot",
  "rust/sliceslice/memmem/prebuilt",
  "rust/std/memmem/oneshot",
  "rust/std/memmem/prebuilt",
  "stringzilla/memmem/oneshot",
]

[[bench]]
model = "count"
name = "huge-ru-john-watson"
regex = 'Джон Уотсон'
haystack = { path = "opensubtitles/ru-huge.txt" }
count = 0
engines = [
  "libc/memmem/oneshot",
  "rust/jetscii/memmem/oneshot",
  "rust/jetscii/memmem/prebuilt",
  "rust/memchr/memmem/oneshot",
  "rust/memchr/memmem/prebuilt",
  "rust/memchr/memmem/twoway",
  "rust/memchr/memmem/rabinkarp",
  "rust/memchr/memmem/wasm32",
  "rust/memchrold/memmem/oneshot",
  "rust/memchrold/memmem/prebuilt",
  "rust/sliceslice/memmem/oneshot",
  "rust/sliceslice/memmem/prebuilt",
  "rust/std/memmem/oneshot",
  "rust/std/memmem/prebuilt",
  "stringzilla/memmem/oneshot",
]

[[bench]]
model = "count"
name = "teeny-ru-john-watson"
regex = 'Джон Уотсон'
haystack = { path = "opensubtitles/ru-teeny.txt" }
count = 0
engines = [
  "libc/memmem/oneshot",
  "rust/jetscii/memmem/oneshot",
  "rust/jetscii/memmem/prebuilt",
  "rust/memchr/memmem/oneshot",
  "rust/memchr/memmem/prebuilt",
  "rust/memchr/memmem/twoway",
  "rust/memchr/memmem/rabinkarp",
  "rust/memchr/memmem/wasm32",
  "rust/memchrold/memmem/oneshot",
  "rust/memchrold/memmem/prebuilt",
  "rust/sliceslice/memmem/oneshot",
  "rust/sliceslice/memmem/prebuilt",
  "rust/std/memmem/oneshot",
  "rust/std/memmem/prebuilt",
  "stringzilla/memmem/oneshot",
]

[[bench]]
model = "count"
name = "huge-zh-john-watson"
regex = '约翰·沃森'
haystack = { path = "opensubtitles/zh-huge.txt" }
count = 0
engines = [
  "libc/memmem/oneshot",
  "rust/jetscii/memmem/oneshot",
  "rust/jetscii/memmem/prebuilt",
  "rust/memchr/memmem/oneshot",
  "rust/memchr/memmem/prebuilt",
  "rust/memchr/memmem/twoway",
  "rust/memchr/memmem/rabinkarp",
  "rust/memchr/memmem/shiftor",
  "rust/memchr/memmem/wasm32",
  "rust/memchrold/memmem/oneshot",
  "rust/memchrold/memmem/prebuilt",
  "rust/sliceslice/memmem/oneshot",
  "rust/sliceslice/memmem/prebuilt",
  "rust/std/memmem/oneshot",
  "rust/std/memmem/prebuilt",
  "stringzilla/memmem/oneshot",
]

[[bench]]
model = "count"
name = "teeny-zh-john-watson"
regex = '约翰·沃森'
haystack = { path = "opensubtitles/zh-teeny.txt" }
count = 0
engines = [
  "libc/memmem/oneshot",
  "rust/jetscii/memmem/oneshot",
  "rust/jetscii/memmem/prebuilt",
  "rust/memchr/memmem/oneshot",
  "rust/memchr/memmem/prebuilt",
  "rust/memchr/memmem/twoway",
  "rust/memchr/memmem/rabinkarp",
  "rust/memchr/memmem/shiftor",
  "rust/memchr/memmem/wasm32",
  "rust/memchrold/memmem/oneshot",
  "rust/memchrold/memmem/prebuilt",
  "rust/sliceslice/memmem/oneshot",
  "rust/sliceslice/memmem/prebuilt",
  "rust/std/memmem/oneshot",
  "rust/std/memmem/prebuilt",
  "stringzilla/memmem/oneshot",
]
